[2022-09-11 21:46:26,160] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tcc_dag.generate-card-trello manual__2022-09-11T21:46:14.988774+00:00 [queued]>
[2022-09-11 21:46:26,172] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tcc_dag.generate-card-trello manual__2022-09-11T21:46:14.988774+00:00 [queued]>
[2022-09-11 21:46:26,173] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-09-11 21:46:26,174] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-09-11 21:46:26,175] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-09-11 21:46:26,191] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): generate-card-trello> on 2022-09-11 21:46:14.988774+00:00
[2022-09-11 21:46:26,198] {standard_task_runner.py:52} INFO - Started process 4063 to run task
[2022-09-11 21:46:26,203] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tcc_dag', 'generate-card-trello', 'manual__2022-09-11T21:46:14.988774+00:00', '--job-id', '582', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/tcc_dag-checkpoint.py', '--cfg-path', '/tmp/tmpsla59750', '--error-file', '/tmp/tmph9wxkp88']
[2022-09-11 21:46:26,205] {standard_task_runner.py:80} INFO - Job 582: Subtask generate-card-trello
[2022-09-11 21:46:26,280] {task_command.py:369} INFO - Running <TaskInstance: tcc_dag.generate-card-trello manual__2022-09-11T21:46:14.988774+00:00 [running]> on host b6ddae3e9f9e
[2022-09-11 21:46:26,370] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Michelle Mesquita
AIRFLOW_CTX_DAG_ID=tcc_dag
AIRFLOW_CTX_TASK_ID=generate-card-trello
AIRFLOW_CTX_EXECUTION_DATE=2022-09-11T21:46:14.988774+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-11T21:46:14.988774+00:00
[2022-09-11 21:46:26,387] {logging_mixin.py:115} INFO - Connecting to the MySQL database...
[2022-09-11 21:46:26,390] {logging_mixin.py:115} INFO - 2003 (HY000): Can't connect to MySQL server on 'localhost:3308' (99)
[2022-09-11 21:46:26,400] {logging_mixin.py:115} INFO - Connecting to the MySQL database...
[2022-09-11 21:46:26,402] {logging_mixin.py:115} INFO - 2003 (HY000): Can't connect to MySQL server on 'localhost:3308' (99)
[2022-09-11 21:46:26,403] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 183, in generate_card_trello
    if len(df1) >0:
TypeError: object of type 'NoneType' has no len()
[2022-09-11 21:46:26,415] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=tcc_dag, task_id=generate-card-trello, execution_date=20220911T214614, start_date=20220911T214626, end_date=20220911T214626
[2022-09-11 21:46:26,430] {standard_task_runner.py:97} ERROR - Failed to execute job 582 for task generate-card-trello (object of type 'NoneType' has no len(); 4063)
[2022-09-11 21:46:26,457] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-11 21:46:26,501] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
