[2022-09-12 03:48:27,325] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tcc_dag.generate-card-trello manual__2022-09-12T03:48:15.104836+00:00 [queued]>
[2022-09-12 03:48:27,349] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tcc_dag.generate-card-trello manual__2022-09-12T03:48:15.104836+00:00 [queued]>
[2022-09-12 03:48:27,351] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-09-12 03:48:27,357] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-09-12 03:48:27,359] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-09-12 03:48:27,382] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): generate-card-trello> on 2022-09-12 03:48:15.104836+00:00
[2022-09-12 03:48:27,388] {standard_task_runner.py:52} INFO - Started process 20201 to run task
[2022-09-12 03:48:27,392] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tcc_dag', 'generate-card-trello', 'manual__2022-09-12T03:48:15.104836+00:00', '--job-id', '643', '--raw', '--subdir', 'DAGS_FOLDER/tcc_dag.py', '--cfg-path', '/tmp/tmpwgv23i8u', '--error-file', '/tmp/tmpkv62dw54']
[2022-09-12 03:48:27,394] {standard_task_runner.py:80} INFO - Job 643: Subtask generate-card-trello
[2022-09-12 03:48:27,463] {task_command.py:369} INFO - Running <TaskInstance: tcc_dag.generate-card-trello manual__2022-09-12T03:48:15.104836+00:00 [running]> on host b6ddae3e9f9e
[2022-09-12 03:48:27,543] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Michelle Mesquita
AIRFLOW_CTX_DAG_ID=tcc_dag
AIRFLOW_CTX_TASK_ID=generate-card-trello
AIRFLOW_CTX_EXECUTION_DATE=2022-09-12T03:48:15.104836+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-12T03:48:15.104836+00:00
[2022-09-12 03:48:27,561] {logging_mixin.py:115} INFO - Connecting to the MySQL database...
[2022-09-12 03:48:27,594] {logging_mixin.py:115} INFO - Database connection closed.
[2022-09-12 03:48:27,628] {logging_mixin.py:115} INFO -             nm_squad  ... id_vulnerability
0  michelleamesquita  ...                0
1  michelleamesquita  ...                1
2  michelleamesquita  ...                2
3  michelleamesquita  ...                3
4  michelleamesquita  ...                4

[5 rows x 14 columns]
[2022-09-12 03:48:27,647] {logging_mixin.py:115} INFO -    id_vulnerability           nm_squad  ... cd_month_end            dt_added
0                 0  michelleamesquita  ...      2022-12 2022-09-08 10:07:47
1                 1  michelleamesquita  ...      2022-10 2022-09-08 10:07:47
2                 2  michelleamesquita  ...      2022-12 2022-09-08 10:07:47
3                 3  michelleamesquita  ...      2022-12 2022-09-08 10:07:47
4                 4  michelleamesquita  ...      2022-12 2022-09-08 10:07:47

[5 rows x 15 columns]
[2022-09-12 03:48:27,649] {logging_mixin.py:115} INFO - Empty DataFrame
Columns: [index, nm_squad, ds_title, nm_repository, in_criticity, dt_created, dt_closed, st_vulnerability, in_deadline, ds_url_issue, nm_source_data, tool, cd_month_start, cd_month_end, id_vulnerability, dt_added]
Index: []
[2022-09-12 03:48:27,650] {logging_mixin.py:115} INFO - 0
[2022-09-12 03:48:27,654] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tcc_dag.py", line 208, in generate_card_trello
    if not df1.empty >0:
AttributeError: 'list' object has no attribute 'empty'
[2022-09-12 03:48:27,669] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=tcc_dag, task_id=generate-card-trello, execution_date=20220912T034815, start_date=20220912T034827, end_date=20220912T034827
[2022-09-12 03:48:27,682] {standard_task_runner.py:97} ERROR - Failed to execute job 643 for task generate-card-trello ('list' object has no attribute 'empty'; 20201)
[2022-09-12 03:48:27,729] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-12 03:48:27,768] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
