[2022-09-10 00:11:49,178] {processor.py:153} INFO - Started process (PID=7126) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 00:11:49,180] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 00:11:49,183] {logging_mixin.py:115} INFO - [2022-09-10 00:11:49,183] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 00:11:49,200] {logging_mixin.py:115} INFO - [2022-09-10 00:11:49,194] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 00:11:49,202] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 00:11:49,280] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.114 seconds
[2022-09-10 00:12:42,869] {processor.py:153} INFO - Started process (PID=7185) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 00:12:42,871] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 00:12:42,873] {logging_mixin.py:115} INFO - [2022-09-10 00:12:42,872] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 00:12:42,887] {logging_mixin.py:115} INFO - [2022-09-10 00:12:42,886] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 00:12:42,888] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 00:12:42,940] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.075 seconds
[2022-09-10 00:28:41,102] {processor.py:153} INFO - Started process (PID=7199) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 00:28:41,161] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 00:28:41,231] {logging_mixin.py:115} INFO - [2022-09-10 00:28:41,219] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 00:28:41,822] {logging_mixin.py:115} INFO - [2022-09-10 00:28:41,692] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 00:28:41,863] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 00:28:44,607] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 4.132 seconds
[2022-09-10 00:29:18,032] {processor.py:153} INFO - Started process (PID=7254) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 00:29:18,035] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 00:29:18,036] {logging_mixin.py:115} INFO - [2022-09-10 00:29:18,036] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 00:29:18,045] {logging_mixin.py:115} INFO - [2022-09-10 00:29:18,044] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 00:29:18,046] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 00:29:18,097] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.071 seconds
[2022-09-10 01:08:02,361] {processor.py:153} INFO - Started process (PID=7262) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 01:08:02,444] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 01:08:02,591] {logging_mixin.py:115} INFO - [2022-09-10 01:08:02,567] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 01:08:03,463] {logging_mixin.py:115} INFO - [2022-09-10 01:08:03,069] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 01:08:03,742] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 01:08:07,133] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 5.319 seconds
[2022-09-10 02:01:44,105] {processor.py:153} INFO - Started process (PID=7317) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 02:01:44,111] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 02:01:44,115] {logging_mixin.py:115} INFO - [2022-09-10 02:01:44,115] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 02:01:44,137] {logging_mixin.py:115} INFO - [2022-09-10 02:01:44,137] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 02:01:44,141] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 02:01:44,222] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.135 seconds
[2022-09-10 02:02:31,442] {processor.py:153} INFO - Started process (PID=7347) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 02:02:31,446] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 02:02:31,449] {logging_mixin.py:115} INFO - [2022-09-10 02:02:31,449] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 02:02:31,473] {logging_mixin.py:115} INFO - [2022-09-10 02:02:31,472] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 02:02:31,478] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 02:02:31,525] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.092 seconds
[2022-09-10 02:55:51,140] {processor.py:153} INFO - Started process (PID=7379) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 02:55:51,142] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 02:55:51,144] {logging_mixin.py:115} INFO - [2022-09-10 02:55:51,143] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 02:55:51,153] {logging_mixin.py:115} INFO - [2022-09-10 02:55:51,152] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 02:55:51,154] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 02:55:51,209] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.074 seconds
[2022-09-10 02:56:36,436] {processor.py:153} INFO - Started process (PID=7427) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 02:56:36,446] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 02:56:36,450] {logging_mixin.py:115} INFO - [2022-09-10 02:56:36,450] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 02:56:36,473] {logging_mixin.py:115} INFO - [2022-09-10 02:56:36,471] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 02:56:36,487] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 02:56:36,705] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.306 seconds
[2022-09-10 03:50:09,040] {processor.py:153} INFO - Started process (PID=7458) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 03:50:09,135] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 03:50:09,202] {logging_mixin.py:115} INFO - [2022-09-10 03:50:09,192] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 03:50:09,696] {logging_mixin.py:115} INFO - [2022-09-10 03:50:09,610] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 03:50:10,013] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 03:50:12,849] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 4.184 seconds
[2022-09-10 03:50:54,407] {processor.py:153} INFO - Started process (PID=7526) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 03:50:54,415] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 03:50:54,428] {logging_mixin.py:115} INFO - [2022-09-10 03:50:54,428] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 03:50:54,444] {logging_mixin.py:115} INFO - [2022-09-10 03:50:54,443] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 03:50:54,446] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 03:50:54,503] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.102 seconds
[2022-09-10 04:44:27,889] {processor.py:153} INFO - Started process (PID=7537) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 04:44:27,915] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 04:44:28,015] {logging_mixin.py:115} INFO - [2022-09-10 04:44:28,012] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 04:44:28,605] {logging_mixin.py:115} INFO - [2022-09-10 04:44:28,435] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 04:44:28,665] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 04:44:32,332] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 5.282 seconds
[2022-09-10 05:11:28,873] {processor.py:153} INFO - Started process (PID=7613) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 05:11:28,874] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 05:11:28,876] {logging_mixin.py:115} INFO - [2022-09-10 05:11:28,876] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 05:11:28,893] {logging_mixin.py:115} INFO - [2022-09-10 05:11:28,892] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 05:11:28,894] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 05:11:28,966] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.108 seconds
[2022-09-10 05:12:18,179] {processor.py:153} INFO - Started process (PID=7665) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 05:12:18,189] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 05:12:18,196] {logging_mixin.py:115} INFO - [2022-09-10 05:12:18,196] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 05:12:18,276] {logging_mixin.py:115} INFO - [2022-09-10 05:12:18,266] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 05:12:18,292] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 05:12:18,505] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.332 seconds
[2022-09-10 05:50:29,728] {processor.py:153} INFO - Started process (PID=7712) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 05:50:29,786] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 05:50:29,841] {logging_mixin.py:115} INFO - [2022-09-10 05:50:29,823] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 05:50:30,089] {logging_mixin.py:115} INFO - [2022-09-10 05:50:30,047] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 05:50:30,128] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 05:50:32,810] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 3.575 seconds
[2022-09-10 05:51:13,738] {processor.py:153} INFO - Started process (PID=7776) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 05:51:13,740] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 05:51:13,743] {logging_mixin.py:115} INFO - [2022-09-10 05:51:13,743] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 05:51:13,759] {logging_mixin.py:115} INFO - [2022-09-10 05:51:13,756] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 05:51:13,764] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 05:51:13,806] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.081 seconds
[2022-09-10 06:44:55,775] {processor.py:153} INFO - Started process (PID=7786) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 06:44:55,975] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 06:44:56,158] {logging_mixin.py:115} INFO - [2022-09-10 06:44:56,157] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 06:44:57,618] {logging_mixin.py:115} INFO - [2022-09-10 06:44:57,301] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 06:44:57,699] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 06:45:03,377] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 8.435 seconds
[2022-09-10 07:38:50,887] {processor.py:153} INFO - Started process (PID=7841) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 07:38:50,941] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 07:38:51,085] {logging_mixin.py:115} INFO - [2022-09-10 07:38:51,083] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 07:38:52,299] {logging_mixin.py:115} INFO - [2022-09-10 07:38:52,206] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 07:38:52,439] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 07:38:57,654] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 7.103 seconds
[2022-09-10 07:39:11,603] {processor.py:153} INFO - Started process (PID=7850) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 07:39:11,708] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 07:39:12,328] {logging_mixin.py:115} INFO - [2022-09-10 07:39:12,285] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 07:39:13,647] {logging_mixin.py:115} INFO - [2022-09-10 07:39:12,773] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 07:39:13,741] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 07:39:19,249] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 9.628 seconds
[2022-09-10 08:33:35,236] {processor.py:153} INFO - Started process (PID=7923) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 08:33:35,240] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 08:33:35,244] {logging_mixin.py:115} INFO - [2022-09-10 08:33:35,243] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 08:33:35,268] {logging_mixin.py:115} INFO - [2022-09-10 08:33:35,260] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 08:33:35,274] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 08:33:35,370] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.146 seconds
[2022-09-10 09:22:41,861] {processor.py:153} INFO - Started process (PID=7951) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 09:22:41,933] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 09:22:41,988] {logging_mixin.py:115} INFO - [2022-09-10 09:22:41,965] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 09:22:42,891] {logging_mixin.py:115} INFO - [2022-09-10 09:22:42,544] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 09:22:42,940] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 09:22:46,502] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 5.956 seconds
[2022-09-10 10:16:46,249] {processor.py:153} INFO - Started process (PID=8006) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 10:16:46,461] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 10:16:46,687] {logging_mixin.py:115} INFO - [2022-09-10 10:16:46,579] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 10:16:47,901] {logging_mixin.py:115} INFO - [2022-09-10 10:16:47,454] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 10:16:48,191] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 10:16:51,975] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 7.065 seconds
[2022-09-10 11:16:12,039] {processor.py:153} INFO - Started process (PID=8077) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 11:16:12,043] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 11:16:12,046] {logging_mixin.py:115} INFO - [2022-09-10 11:16:12,046] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 11:16:12,086] {logging_mixin.py:115} INFO - [2022-09-10 11:16:12,085] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 11:16:12,087] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 11:16:12,172] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.138 seconds
[2022-09-10 11:16:51,955] {processor.py:153} INFO - Started process (PID=8131) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 11:16:52,035] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 11:16:52,156] {logging_mixin.py:115} INFO - [2022-09-10 11:16:52,153] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 11:16:52,472] {logging_mixin.py:115} INFO - [2022-09-10 11:16:52,395] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 11:16:52,537] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 11:16:56,217] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 5.145 seconds
[2022-09-10 12:05:17,389] {processor.py:153} INFO - Started process (PID=8178) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 12:05:17,392] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 12:05:17,395] {logging_mixin.py:115} INFO - [2022-09-10 12:05:17,395] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 12:05:17,411] {logging_mixin.py:115} INFO - [2022-09-10 12:05:17,408] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 12:05:17,414] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 12:05:17,464] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.085 seconds
[2022-09-10 12:06:19,711] {processor.py:153} INFO - Started process (PID=8217) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 12:06:19,717] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 12:06:19,762] {logging_mixin.py:115} INFO - [2022-09-10 12:06:19,739] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 12:06:19,809] {logging_mixin.py:115} INFO - [2022-09-10 12:06:19,806] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 12:06:19,814] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 12:06:20,369] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.689 seconds
[2022-09-10 12:06:51,486] {processor.py:153} INFO - Started process (PID=8274) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 12:06:51,490] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 12:06:51,494] {logging_mixin.py:115} INFO - [2022-09-10 12:06:51,494] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 12:06:51,521] {logging_mixin.py:115} INFO - [2022-09-10 12:06:51,517] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 12:06:51,524] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 12:06:51,591] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.116 seconds
[2022-09-10 12:59:29,459] {processor.py:153} INFO - Started process (PID=8313) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 12:59:29,461] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 12:59:29,464] {logging_mixin.py:115} INFO - [2022-09-10 12:59:29,464] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 12:59:29,484] {logging_mixin.py:115} INFO - [2022-09-10 12:59:29,482] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 12:59:29,488] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 12:59:29,601] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.151 seconds
[2022-09-10 13:00:23,515] {processor.py:153} INFO - Started process (PID=8378) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 13:00:23,517] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 13:00:23,520] {logging_mixin.py:115} INFO - [2022-09-10 13:00:23,520] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 13:00:23,535] {logging_mixin.py:115} INFO - [2022-09-10 13:00:23,534] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 13:00:23,536] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 13:00:23,596] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.092 seconds
[2022-09-10 13:53:58,040] {processor.py:153} INFO - Started process (PID=8401) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 13:53:58,072] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 13:53:58,095] {logging_mixin.py:115} INFO - [2022-09-10 13:53:58,092] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 13:53:58,795] {logging_mixin.py:115} INFO - [2022-09-10 13:53:58,742] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 13:53:58,826] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 13:54:02,556] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 4.784 seconds
[2022-09-10 14:48:37,224] {processor.py:153} INFO - Started process (PID=8479) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 14:48:37,229] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 14:48:37,241] {logging_mixin.py:115} INFO - [2022-09-10 14:48:37,240] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 14:48:37,258] {logging_mixin.py:115} INFO - [2022-09-10 14:48:37,256] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 14:48:37,262] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 14:48:37,345] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.145 seconds
[2022-09-10 14:55:09,578] {processor.py:153} INFO - Started process (PID=8518) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 14:55:09,736] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 14:55:09,903] {logging_mixin.py:115} INFO - [2022-09-10 14:55:09,859] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 14:55:10,658] {logging_mixin.py:115} INFO - [2022-09-10 14:55:10,408] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 14:55:10,774] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 14:55:15,365] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 6.843 seconds
[2022-09-10 15:10:31,413] {processor.py:153} INFO - Started process (PID=8567) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 15:10:31,464] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 15:10:31,508] {logging_mixin.py:115} INFO - [2022-09-10 15:10:31,507] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 15:10:31,832] {logging_mixin.py:115} INFO - [2022-09-10 15:10:31,776] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 15:10:31,881] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 15:10:36,558] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 5.394 seconds
[2022-09-10 15:11:11,024] {processor.py:153} INFO - Started process (PID=8598) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 15:11:11,028] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 15:11:11,036] {logging_mixin.py:115} INFO - [2022-09-10 15:11:11,033] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 15:11:11,053] {logging_mixin.py:115} INFO - [2022-09-10 15:11:11,049] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 15:11:11,055] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 15:11:11,110] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.101 seconds
[2022-09-10 15:50:31,044] {processor.py:153} INFO - Started process (PID=8632) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 15:50:31,112] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 15:50:31,733] {logging_mixin.py:115} INFO - [2022-09-10 15:50:31,673] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 15:50:32,988] {logging_mixin.py:115} INFO - [2022-09-10 15:50:32,811] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 15:50:33,103] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 15:50:36,825] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 6.407 seconds
[2022-09-10 15:51:16,868] {processor.py:153} INFO - Started process (PID=8694) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 15:51:16,869] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 15:51:16,871] {logging_mixin.py:115} INFO - [2022-09-10 15:51:16,871] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 15:51:16,880] {logging_mixin.py:115} INFO - [2022-09-10 15:51:16,879] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 15:51:16,881] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 15:51:16,928] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.071 seconds
[2022-09-10 16:44:49,097] {processor.py:153} INFO - Started process (PID=8704) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 16:44:49,164] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 16:44:49,382] {logging_mixin.py:115} INFO - [2022-09-10 16:44:49,284] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 16:44:50,410] {logging_mixin.py:115} INFO - [2022-09-10 16:44:50,123] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 16:44:50,471] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 16:44:53,617] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 5.588 seconds
[2022-09-10 17:38:38,680] {processor.py:153} INFO - Started process (PID=8760) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 17:38:38,711] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 17:38:38,732] {logging_mixin.py:115} INFO - [2022-09-10 17:38:38,732] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 17:38:38,742] {logging_mixin.py:115} INFO - [2022-09-10 17:38:38,741] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 17:38:38,744] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 17:38:38,790] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.128 seconds
[2022-09-10 17:39:25,669] {processor.py:153} INFO - Started process (PID=8807) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 17:39:25,680] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 17:39:25,703] {logging_mixin.py:115} INFO - [2022-09-10 17:39:25,702] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 17:39:25,723] {logging_mixin.py:115} INFO - [2022-09-10 17:39:25,719] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 17:39:25,725] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 17:39:25,895] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.236 seconds
[2022-09-10 18:32:56,924] {processor.py:153} INFO - Started process (PID=8844) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 18:32:56,966] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 18:32:57,030] {logging_mixin.py:115} INFO - [2022-09-10 18:32:57,029] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 18:32:57,605] {logging_mixin.py:115} INFO - [2022-09-10 18:32:57,382] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 18:32:57,691] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 18:33:00,349] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 4.242 seconds
[2022-09-10 18:33:39,236] {processor.py:153} INFO - Started process (PID=8910) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 18:33:39,238] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 18:33:39,240] {logging_mixin.py:115} INFO - [2022-09-10 18:33:39,240] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 18:33:39,251] {logging_mixin.py:115} INFO - [2022-09-10 18:33:39,250] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 18:33:39,255] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 18:33:39,305] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.076 seconds
[2022-09-10 19:27:20,693] {processor.py:153} INFO - Started process (PID=8921) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 19:27:20,872] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 19:27:21,000] {logging_mixin.py:115} INFO - [2022-09-10 19:27:20,997] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 19:27:21,622] {logging_mixin.py:115} INFO - [2022-09-10 19:27:21,411] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 19:27:21,705] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 19:27:24,149] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 4.395 seconds
[2022-09-10 19:27:56,700] {processor.py:153} INFO - Started process (PID=8978) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 19:27:56,755] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 19:27:56,886] {logging_mixin.py:115} INFO - [2022-09-10 19:27:56,884] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 19:27:57,036] {logging_mixin.py:115} INFO - [2022-09-10 19:27:57,010] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 19:27:57,058] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 19:27:57,649] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 1.199 seconds
[2022-09-10 20:21:30,163] {processor.py:153} INFO - Started process (PID=8987) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 20:21:30,196] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 20:21:30,228] {logging_mixin.py:115} INFO - [2022-09-10 20:21:30,226] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 20:21:30,707] {logging_mixin.py:115} INFO - [2022-09-10 20:21:30,555] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 20:21:30,899] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 20:21:35,712] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 6.118 seconds
[2022-09-10 20:31:25,394] {processor.py:153} INFO - Started process (PID=9053) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 20:31:25,448] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 20:31:25,452] {logging_mixin.py:115} INFO - [2022-09-10 20:31:25,452] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 20:31:25,470] {logging_mixin.py:115} INFO - [2022-09-10 20:31:25,467] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 20:31:25,477] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 20:31:25,558] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.185 seconds
[2022-09-10 20:48:36,809] {processor.py:153} INFO - Started process (PID=9098) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 20:48:36,973] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 20:48:37,208] {logging_mixin.py:115} INFO - [2022-09-10 20:48:37,165] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 20:48:38,100] {logging_mixin.py:115} INFO - [2022-09-10 20:48:37,775] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 20:48:38,222] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 20:48:42,785] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 6.821 seconds
[2022-09-10 20:49:40,132] {processor.py:153} INFO - Started process (PID=9167) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 20:49:40,149] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 20:49:40,153] {logging_mixin.py:115} INFO - [2022-09-10 20:49:40,153] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 20:49:40,177] {logging_mixin.py:115} INFO - [2022-09-10 20:49:40,175] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 20:49:40,180] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 20:49:40,351] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.236 seconds
[2022-09-10 21:06:04,086] {processor.py:153} INFO - Started process (PID=9225) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 21:06:04,136] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 21:06:04,278] {logging_mixin.py:115} INFO - [2022-09-10 21:06:04,260] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 21:06:04,998] {logging_mixin.py:115} INFO - [2022-09-10 21:06:04,720] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 21:06:05,109] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 21:06:12,417] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 9.484 seconds
[2022-09-10 21:23:12,164] {processor.py:153} INFO - Started process (PID=9249) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 21:23:12,171] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 21:23:12,173] {logging_mixin.py:115} INFO - [2022-09-10 21:23:12,173] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 21:23:12,199] {logging_mixin.py:115} INFO - [2022-09-10 21:23:12,198] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 21:23:12,202] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 21:23:12,360] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.221 seconds
[2022-09-10 21:24:00,897] {processor.py:153} INFO - Started process (PID=9300) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 21:24:00,907] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 21:24:00,912] {logging_mixin.py:115} INFO - [2022-09-10 21:24:00,910] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 21:24:00,933] {logging_mixin.py:115} INFO - [2022-09-10 21:24:00,928] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 21:24:00,937] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 21:24:01,079] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.194 seconds
[2022-09-10 21:40:14,537] {processor.py:153} INFO - Started process (PID=9335) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 21:40:14,539] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 21:40:14,541] {logging_mixin.py:115} INFO - [2022-09-10 21:40:14,541] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 21:40:14,551] {logging_mixin.py:115} INFO - [2022-09-10 21:40:14,550] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 21:40:14,553] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 21:40:14,587] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.056 seconds
[2022-09-10 21:41:23,412] {processor.py:153} INFO - Started process (PID=9407) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 21:41:23,416] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 21:41:23,421] {logging_mixin.py:115} INFO - [2022-09-10 21:41:23,420] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 21:41:23,441] {logging_mixin.py:115} INFO - [2022-09-10 21:41:23,434] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 21:41:23,444] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 21:41:23,500] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.105 seconds
[2022-09-10 21:59:22,269] {processor.py:153} INFO - Started process (PID=9446) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 21:59:22,279] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 21:59:22,297] {logging_mixin.py:115} INFO - [2022-09-10 21:59:22,296] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 21:59:22,331] {logging_mixin.py:115} INFO - [2022-09-10 21:59:22,330] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 21:59:22,341] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 21:59:22,630] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.392 seconds
[2022-09-10 22:16:03,914] {processor.py:153} INFO - Started process (PID=9485) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 22:16:03,915] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 22:16:03,917] {logging_mixin.py:115} INFO - [2022-09-10 22:16:03,917] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 22:16:03,927] {logging_mixin.py:115} INFO - [2022-09-10 22:16:03,926] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 22:16:03,928] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 22:16:03,957] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.047 seconds
[2022-09-10 22:16:53,771] {processor.py:153} INFO - Started process (PID=9529) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 22:16:53,784] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 22:16:53,796] {logging_mixin.py:115} INFO - [2022-09-10 22:16:53,796] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 22:16:53,830] {logging_mixin.py:115} INFO - [2022-09-10 22:16:53,828] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 22:16:53,837] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 22:16:54,006] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.252 seconds
[2022-09-10 22:34:17,248] {processor.py:153} INFO - Started process (PID=9565) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 22:34:17,250] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 22:34:17,253] {logging_mixin.py:115} INFO - [2022-09-10 22:34:17,253] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 22:34:17,265] {logging_mixin.py:115} INFO - [2022-09-10 22:34:17,264] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 22:34:17,266] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 22:34:20,070] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 2.818 seconds
[2022-09-10 22:35:03,850] {processor.py:153} INFO - Started process (PID=9619) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 22:35:03,852] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 22:35:03,857] {logging_mixin.py:115} INFO - [2022-09-10 22:35:03,857] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 22:35:03,881] {logging_mixin.py:115} INFO - [2022-09-10 22:35:03,875] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 22:35:03,883] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 22:35:03,984] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.153 seconds
[2022-09-10 23:12:20,299] {processor.py:153} INFO - Started process (PID=9646) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 23:12:20,448] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 23:12:20,564] {logging_mixin.py:115} INFO - [2022-09-10 23:12:20,550] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 23:12:21,499] {logging_mixin.py:115} INFO - [2022-09-10 23:12:21,364] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 23:12:21,544] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 23:12:25,164] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 5.556 seconds
[2022-09-10 23:13:20,988] {processor.py:153} INFO - Started process (PID=9711) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 23:13:20,991] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 23:13:20,995] {logging_mixin.py:115} INFO - [2022-09-10 23:13:20,994] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 23:13:21,021] {logging_mixin.py:115} INFO - [2022-09-10 23:13:21,017] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 23:13:21,025] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 23:13:21,139] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.165 seconds
[2022-09-10 23:13:51,417] {processor.py:153} INFO - Started process (PID=9768) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 23:13:51,422] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 23:13:51,427] {logging_mixin.py:115} INFO - [2022-09-10 23:13:51,426] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 23:13:51,444] {logging_mixin.py:115} INFO - [2022-09-10 23:13:51,443] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 23:13:51,446] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 23:13:51,491] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.083 seconds
[2022-09-10 23:14:21,886] {processor.py:153} INFO - Started process (PID=9832) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 23:14:21,891] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 23:14:21,894] {logging_mixin.py:115} INFO - [2022-09-10 23:14:21,894] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 23:14:21,921] {logging_mixin.py:115} INFO - [2022-09-10 23:14:21,919] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 23:14:21,924] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 23:14:21,975] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.096 seconds
[2022-09-10 23:14:52,597] {processor.py:153} INFO - Started process (PID=9889) to work on /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 23:14:52,600] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py for tasks to queue
[2022-09-10 23:14:52,603] {logging_mixin.py:115} INFO - [2022-09-10 23:14:52,603] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 23:14:52,617] {logging_mixin.py:115} INFO - [2022-09-10 23:14:52,616] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 112
    query = f"""UPDATE mydatabase.security set st_vulnerability = '{jira_status[i]}',dh_updated='{datetime.now()}' where ds_url_issue = '{row['ds_url_issue'][index]}'""""
                                                                                                                                                                         ^
SyntaxError: EOL while scanning string literal
[2022-09-10 23:14:52,620] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py
[2022-09-10 23:14:52,685] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py took 0.096 seconds
