[2022-09-09 01:36:51,430] {processor.py:153} INFO - Started process (PID=56) to work on /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py
[2022-09-09 01:36:51,435] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py for tasks to queue
[2022-09-09 01:36:51,436] {logging_mixin.py:115} INFO - [2022-09-09 01:36:51,436] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py
[2022-09-09 01:36:52,023] {logging_mixin.py:115} INFO - [2022-09-09 01:36:52,020] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py", line 8, in <module>
    project_id=sys.argv[1]
NameError: name 'sys' is not defined
[2022-09-09 01:36:52,029] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py
[2022-09-09 01:36:52,058] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py took 0.632 seconds
[2022-09-09 01:37:22,356] {processor.py:153} INFO - Started process (PID=131) to work on /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py
[2022-09-09 01:37:22,372] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py for tasks to queue
[2022-09-09 01:37:22,374] {logging_mixin.py:115} INFO - [2022-09-09 01:37:22,374] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py
[2022-09-09 01:37:22,855] {logging_mixin.py:115} INFO - [2022-09-09 01:37:22,851] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py", line 8, in <module>
    project_id=sys.argv[1]
NameError: name 'sys' is not defined
[2022-09-09 01:37:22,856] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py
[2022-09-09 01:37:22,894] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py took 0.543 seconds
[2022-09-09 01:37:53,464] {processor.py:153} INFO - Started process (PID=212) to work on /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py
[2022-09-09 01:37:53,466] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py for tasks to queue
[2022-09-09 01:37:53,469] {logging_mixin.py:115} INFO - [2022-09-09 01:37:53,468] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py
[2022-09-09 01:37:53,844] {logging_mixin.py:115} INFO - [2022-09-09 01:37:53,842] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py", line 8, in <module>
    project_id=sys.argv[1]
NameError: name 'sys' is not defined
[2022-09-09 01:37:53,847] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py
[2022-09-09 01:37:53,872] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py took 0.413 seconds
[2022-09-09 01:39:05,174] {processor.py:153} INFO - Started process (PID=49) to work on /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py
[2022-09-09 01:39:05,179] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py for tasks to queue
[2022-09-09 01:39:05,182] {logging_mixin.py:115} INFO - [2022-09-09 01:39:05,182] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py
[2022-09-09 01:39:05,991] {logging_mixin.py:115} INFO - [2022-09-09 01:39:05,988] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py", line 8, in <module>
    project_id=sys.argv[1]
NameError: name 'sys' is not defined
[2022-09-09 01:39:05,993] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py
[2022-09-09 01:39:06,031] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py took 0.861 seconds
[2022-09-09 01:39:36,550] {processor.py:153} INFO - Started process (PID=122) to work on /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py
[2022-09-09 01:39:36,561] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py for tasks to queue
[2022-09-09 01:39:36,562] {logging_mixin.py:115} INFO - [2022-09-09 01:39:36,562] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py
[2022-09-09 01:39:37,186] {logging_mixin.py:115} INFO - [2022-09-09 01:39:37,184] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py", line 8, in <module>
    project_id=sys.argv[1]
NameError: name 'sys' is not defined
[2022-09-09 01:39:37,187] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py
[2022-09-09 01:39:37,208] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py took 0.661 seconds
[2022-09-09 01:40:07,435] {processor.py:153} INFO - Started process (PID=208) to work on /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py
[2022-09-09 01:40:07,441] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py for tasks to queue
[2022-09-09 01:40:07,443] {logging_mixin.py:115} INFO - [2022-09-09 01:40:07,442] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py
[2022-09-09 01:40:07,978] {logging_mixin.py:115} INFO - [2022-09-09 01:40:07,975] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py", line 8, in <module>
    project_id=sys.argv[1]
NameError: name 'sys' is not defined
[2022-09-09 01:40:07,980] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py
[2022-09-09 01:40:08,008] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py took 0.598 seconds
[2022-09-09 01:40:38,211] {processor.py:153} INFO - Started process (PID=286) to work on /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py
[2022-09-09 01:40:38,215] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py for tasks to queue
[2022-09-09 01:40:38,217] {logging_mixin.py:115} INFO - [2022-09-09 01:40:38,217] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py
[2022-09-09 01:40:38,672] {logging_mixin.py:115} INFO - [2022-09-09 01:40:38,670] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py", line 8, in <module>
    project_id=sys.argv[1]
NameError: name 'sys' is not defined
[2022-09-09 01:40:38,673] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py
[2022-09-09 01:40:38,696] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/gitlab-extract-data-checkpoint.py took 0.489 seconds
