[2022-09-09 01:36:50,628] {processor.py:153} INFO - Started process (PID=52) to work on /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py
[2022-09-09 01:36:50,630] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py for tasks to queue
[2022-09-09 01:36:50,631] {logging_mixin.py:115} INFO - [2022-09-09 01:36:50,631] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py
[2022-09-09 01:36:51,333] {logging_mixin.py:115} INFO - [2022-09-09 01:36:51,330] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py", line 9, in <module>
    f = open('snyk_token.json')
FileNotFoundError: [Errno 2] No such file or directory: 'snyk_token.json'
[2022-09-09 01:36:51,335] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py
[2022-09-09 01:36:51,365] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py took 0.750 seconds
[2022-09-09 01:37:21,851] {processor.py:153} INFO - Started process (PID=127) to work on /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py
[2022-09-09 01:37:21,853] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py for tasks to queue
[2022-09-09 01:37:21,854] {logging_mixin.py:115} INFO - [2022-09-09 01:37:21,854] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py
[2022-09-09 01:37:22,267] {logging_mixin.py:115} INFO - [2022-09-09 01:37:22,265] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py", line 9, in <module>
    f = open('snyk_token.json')
FileNotFoundError: [Errno 2] No such file or directory: 'snyk_token.json'
[2022-09-09 01:37:22,268] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py
[2022-09-09 01:37:22,309] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py took 0.462 seconds
[2022-09-09 01:37:52,985] {processor.py:153} INFO - Started process (PID=209) to work on /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py
[2022-09-09 01:37:52,986] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py for tasks to queue
[2022-09-09 01:37:52,987] {logging_mixin.py:115} INFO - [2022-09-09 01:37:52,987] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py
[2022-09-09 01:37:53,394] {logging_mixin.py:115} INFO - [2022-09-09 01:37:53,391] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py", line 9, in <module>
    f = open('snyk_token.json')
FileNotFoundError: [Errno 2] No such file or directory: 'snyk_token.json'
[2022-09-09 01:37:53,396] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py
[2022-09-09 01:37:53,418] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py took 0.437 seconds
[2022-09-09 01:39:03,736] {processor.py:153} INFO - Started process (PID=45) to work on /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py
[2022-09-09 01:39:03,744] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py for tasks to queue
[2022-09-09 01:39:03,746] {logging_mixin.py:115} INFO - [2022-09-09 01:39:03,745] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py
[2022-09-09 01:39:04,983] {logging_mixin.py:115} INFO - [2022-09-09 01:39:04,976] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py", line 9, in <module>
    f = open('snyk_token.json')
FileNotFoundError: [Errno 2] No such file or directory: 'snyk_token.json'
[2022-09-09 01:39:04,985] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py
[2022-09-09 01:39:05,057] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py took 1.323 seconds
[2022-09-09 01:39:35,260] {processor.py:153} INFO - Started process (PID=118) to work on /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py
[2022-09-09 01:39:35,261] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py for tasks to queue
[2022-09-09 01:39:35,262] {logging_mixin.py:115} INFO - [2022-09-09 01:39:35,262] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py
[2022-09-09 01:39:35,647] {logging_mixin.py:115} INFO - [2022-09-09 01:39:35,644] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py", line 9, in <module>
    f = open('snyk_token.json')
FileNotFoundError: [Errno 2] No such file or directory: 'snyk_token.json'
[2022-09-09 01:39:35,648] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py
[2022-09-09 01:39:35,667] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py took 0.411 seconds
[2022-09-09 01:40:06,364] {processor.py:153} INFO - Started process (PID=205) to work on /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py
[2022-09-09 01:40:06,366] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py for tasks to queue
[2022-09-09 01:40:06,368] {logging_mixin.py:115} INFO - [2022-09-09 01:40:06,368] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py
[2022-09-09 01:40:06,863] {logging_mixin.py:115} INFO - [2022-09-09 01:40:06,860] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py", line 9, in <module>
    f = open('snyk_token.json')
FileNotFoundError: [Errno 2] No such file or directory: 'snyk_token.json'
[2022-09-09 01:40:06,865] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py
[2022-09-09 01:40:06,898] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py took 0.541 seconds
[2022-09-09 01:40:37,748] {processor.py:153} INFO - Started process (PID=281) to work on /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py
[2022-09-09 01:40:37,750] {processor.py:641} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py for tasks to queue
[2022-09-09 01:40:37,752] {logging_mixin.py:115} INFO - [2022-09-09 01:40:37,752] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py
[2022-09-09 01:40:38,140] {logging_mixin.py:115} INFO - [2022-09-09 01:40:38,138] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py", line 9, in <module>
    f = open('snyk_token.json')
FileNotFoundError: [Errno 2] No such file or directory: 'snyk_token.json'
[2022-09-09 01:40:38,141] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py
[2022-09-09 01:40:38,163] {processor.py:161} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/snyk-extract-data-checkpoint.py took 0.419 seconds
