[2022-09-12 03:31:42,246] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tcc_dag.add-db-data manual__2022-09-12T03:31:34.546636+00:00 [queued]>
[2022-09-12 03:31:42,264] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tcc_dag.add-db-data manual__2022-09-12T03:31:34.546636+00:00 [queued]>
[2022-09-12 03:31:42,266] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-09-12 03:31:42,267] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-09-12 03:31:42,268] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-09-12 03:31:42,292] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): add-db-data> on 2022-09-12 03:31:34.546636+00:00
[2022-09-12 03:31:42,304] {standard_task_runner.py:52} INFO - Started process 19176 to run task
[2022-09-12 03:31:42,308] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tcc_dag', 'add-db-data', 'manual__2022-09-12T03:31:34.546636+00:00', '--job-id', '622', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/tcc_dag-checkpoint.py', '--cfg-path', '/tmp/tmpknaxm4m8', '--error-file', '/tmp/tmpokp8g1hd']
[2022-09-12 03:31:42,310] {standard_task_runner.py:80} INFO - Job 622: Subtask add-db-data
[2022-09-12 03:31:42,397] {task_command.py:369} INFO - Running <TaskInstance: tcc_dag.add-db-data manual__2022-09-12T03:31:34.546636+00:00 [running]> on host b6ddae3e9f9e
[2022-09-12 03:31:42,485] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Michelle Mesquita
AIRFLOW_CTX_DAG_ID=tcc_dag
AIRFLOW_CTX_TASK_ID=add-db-data
AIRFLOW_CTX_EXECUTION_DATE=2022-09-12T03:31:34.546636+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-12T03:31:34.546636+00:00
[2022-09-12 03:31:42,503] {logging_mixin.py:115} INFO - Connecting to the MySQL database...
[2022-09-12 03:31:42,506] {logging_mixin.py:115} INFO - 2003 (HY000): Can't connect to MySQL server on 'localhost:3308' (99)
[2022-09-12 03:31:42,544] {logging_mixin.py:115} INFO -             nm_squad  ... id_vulnerability
0  michelleamesquita  ...                0
1  michelleamesquita  ...                1
2  michelleamesquita  ...                2
3  michelleamesquita  ...                3
4  michelleamesquita  ...                4

[5 rows x 14 columns]
[2022-09-12 03:31:42,546] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 117, in add_db_data
    print(df_db.head())
AttributeError: 'NoneType' object has no attribute 'head'
[2022-09-12 03:31:42,571] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=tcc_dag, task_id=add-db-data, execution_date=20220912T033134, start_date=20220912T033142, end_date=20220912T033142
[2022-09-12 03:31:42,585] {standard_task_runner.py:97} ERROR - Failed to execute job 622 for task add-db-data ('NoneType' object has no attribute 'head'; 19176)
[2022-09-12 03:31:42,607] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-12 03:31:42,661] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
