[2022-09-12 04:09:00,186] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tcc_dag.generate-card-trello manual__2022-09-12T04:08:48.460693+00:00 [queued]>
[2022-09-12 04:09:00,196] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tcc_dag.generate-card-trello manual__2022-09-12T04:08:48.460693+00:00 [queued]>
[2022-09-12 04:09:00,197] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-09-12 04:09:00,198] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-09-12 04:09:00,199] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-09-12 04:09:00,214] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): generate-card-trello> on 2022-09-12 04:08:48.460693+00:00
[2022-09-12 04:09:00,220] {standard_task_runner.py:52} INFO - Started process 21471 to run task
[2022-09-12 04:09:00,223] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tcc_dag', 'generate-card-trello', 'manual__2022-09-12T04:08:48.460693+00:00', '--job-id', '669', '--raw', '--subdir', 'DAGS_FOLDER/tcc_dag.py', '--cfg-path', '/tmp/tmp_ipl1yy8', '--error-file', '/tmp/tmp_kqj_nfe']
[2022-09-12 04:09:00,225] {standard_task_runner.py:80} INFO - Job 669: Subtask generate-card-trello
[2022-09-12 04:09:00,290] {task_command.py:369} INFO - Running <TaskInstance: tcc_dag.generate-card-trello manual__2022-09-12T04:08:48.460693+00:00 [running]> on host b6ddae3e9f9e
[2022-09-12 04:09:00,363] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Michelle Mesquita
AIRFLOW_CTX_DAG_ID=tcc_dag
AIRFLOW_CTX_TASK_ID=generate-card-trello
AIRFLOW_CTX_EXECUTION_DATE=2022-09-12T04:08:48.460693+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-12T04:08:48.460693+00:00
[2022-09-12 04:09:00,375] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tcc_dag.py", line 192, in generate_card_trello
    df_diff2 = pd.read_csv('./dags/tmp2.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: './dags/tmp2.csv'
[2022-09-12 04:09:00,387] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=tcc_dag, task_id=generate-card-trello, execution_date=20220912T040848, start_date=20220912T040900, end_date=20220912T040900
[2022-09-12 04:09:00,412] {standard_task_runner.py:97} ERROR - Failed to execute job 669 for task generate-card-trello ([Errno 2] No such file or directory: './dags/tmp2.csv'; 21471)
[2022-09-12 04:09:00,438] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-12 04:09:00,496] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
