[2022-09-12 01:54:29,345] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tcc_dag.add-db-data manual__2022-09-12T01:54:21.429512+00:00 [queued]>
[2022-09-12 01:54:29,362] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tcc_dag.add-db-data manual__2022-09-12T01:54:21.429512+00:00 [queued]>
[2022-09-12 01:54:29,364] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-09-12 01:54:29,364] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-09-12 01:54:29,365] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-09-12 01:54:29,383] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): add-db-data> on 2022-09-12 01:54:21.429512+00:00
[2022-09-12 01:54:29,391] {standard_task_runner.py:52} INFO - Started process 14023 to run task
[2022-09-12 01:54:29,396] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tcc_dag', 'add-db-data', 'manual__2022-09-12T01:54:21.429512+00:00', '--job-id', '597', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/tcc_dag-checkpoint.py', '--cfg-path', '/tmp/tmpg3vglg_3', '--error-file', '/tmp/tmpy6urqzv0']
[2022-09-12 01:54:29,398] {standard_task_runner.py:80} INFO - Job 597: Subtask add-db-data
[2022-09-12 01:54:29,472] {task_command.py:369} INFO - Running <TaskInstance: tcc_dag.add-db-data manual__2022-09-12T01:54:21.429512+00:00 [running]> on host b6ddae3e9f9e
[2022-09-12 01:54:29,566] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Michelle Mesquita
AIRFLOW_CTX_DAG_ID=tcc_dag
AIRFLOW_CTX_TASK_ID=add-db-data
AIRFLOW_CTX_EXECUTION_DATE=2022-09-12T01:54:21.429512+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-12T01:54:21.429512+00:00
[2022-09-12 01:54:29,584] {logging_mixin.py:115} INFO - Connecting to the MySQL database...
[2022-09-12 01:54:29,588] {logging_mixin.py:115} INFO - 2003 (HY000): Can't connect to MySQL server on 'localhost:3308' (99)
[2022-09-12 01:54:29,599] {logging_mixin.py:115} INFO - 12
[2022-09-12 01:54:29,600] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 127, in add_db_data
    df_diff1.index  = df_diff.index + len(df_db)
TypeError: object of type 'NoneType' has no len()
[2022-09-12 01:54:29,614] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=tcc_dag, task_id=add-db-data, execution_date=20220912T015421, start_date=20220912T015429, end_date=20220912T015429
[2022-09-12 01:54:29,629] {standard_task_runner.py:97} ERROR - Failed to execute job 597 for task add-db-data (object of type 'NoneType' has no len(); 14023)
[2022-09-12 01:54:29,653] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-12 01:54:29,706] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
