[2022-09-11 21:30:59,846] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tcc_dag.add-db-data manual__2022-09-11T21:30:51.277988+00:00 [queued]>
[2022-09-11 21:30:59,860] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tcc_dag.add-db-data manual__2022-09-11T21:30:51.277988+00:00 [queued]>
[2022-09-11 21:30:59,861] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-09-11 21:30:59,862] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-09-11 21:30:59,863] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-09-11 21:30:59,878] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): add-db-data> on 2022-09-11 21:30:51.277988+00:00
[2022-09-11 21:30:59,884] {standard_task_runner.py:52} INFO - Started process 2947 to run task
[2022-09-11 21:30:59,888] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tcc_dag', 'add-db-data', 'manual__2022-09-11T21:30:51.277988+00:00', '--job-id', '544', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/tcc_dag-checkpoint.py', '--cfg-path', '/tmp/tmpxluzhut1', '--error-file', '/tmp/tmpm8ih3h36']
[2022-09-11 21:30:59,890] {standard_task_runner.py:80} INFO - Job 544: Subtask add-db-data
[2022-09-11 21:30:59,954] {task_command.py:369} INFO - Running <TaskInstance: tcc_dag.add-db-data manual__2022-09-11T21:30:51.277988+00:00 [running]> on host b6ddae3e9f9e
[2022-09-11 21:31:00,034] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Michelle Mesquita
AIRFLOW_CTX_DAG_ID=tcc_dag
AIRFLOW_CTX_TASK_ID=add-db-data
AIRFLOW_CTX_EXECUTION_DATE=2022-09-11T21:30:51.277988+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-11T21:30:51.277988+00:00
[2022-09-11 21:31:00,049] {logging_mixin.py:115} INFO - Connecting to the MySQL database...
[2022-09-11 21:31:00,051] {logging_mixin.py:115} INFO - 2003 (HY000): Can't connect to MySQL server on 'localhost:3308' (99)
[2022-09-11 21:31:00,061] {logging_mixin.py:115} INFO - Connecting to the MySQL database...
[2022-09-11 21:31:00,063] {logging_mixin.py:115} INFO - 2003 (HY000): Can't connect to MySQL server on 'localhost:3308' (99)
[2022-09-11 21:31:00,066] {logging_mixin.py:115} INFO - Connecting to the MySQL database...
[2022-09-11 21:31:00,068] {logging_mixin.py:115} INFO - 2003 (HY000): Can't connect to MySQL server on 'localhost:3308' (99)
[2022-09-11 21:31:00,069] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 138, in add_db_data
    if len(df_diff2) >0:
TypeError: object of type 'NoneType' has no len()
[2022-09-11 21:31:00,082] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=tcc_dag, task_id=add-db-data, execution_date=20220911T213051, start_date=20220911T213059, end_date=20220911T213100
[2022-09-11 21:31:00,094] {standard_task_runner.py:97} ERROR - Failed to execute job 544 for task add-db-data (object of type 'NoneType' has no len(); 2947)
[2022-09-11 21:31:00,143] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-11 21:31:00,188] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
