[2022-09-11 21:41:13,946] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tcc_dag.add-db-data manual__2022-09-11T21:41:04.436761+00:00 [queued]>
[2022-09-11 21:41:13,959] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tcc_dag.add-db-data manual__2022-09-11T21:41:04.436761+00:00 [queued]>
[2022-09-11 21:41:13,960] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-09-11 21:41:13,961] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-09-11 21:41:13,962] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-09-11 21:41:13,979] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): add-db-data> on 2022-09-11 21:41:04.436761+00:00
[2022-09-11 21:41:13,986] {standard_task_runner.py:52} INFO - Started process 3699 to run task
[2022-09-11 21:41:13,990] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tcc_dag', 'add-db-data', 'manual__2022-09-11T21:41:04.436761+00:00', '--job-id', '569', '--raw', '--subdir', 'DAGS_FOLDER/tcc_dag.py', '--cfg-path', '/tmp/tmpi_qh69dd', '--error-file', '/tmp/tmptq_uvcoq']
[2022-09-11 21:41:13,992] {standard_task_runner.py:80} INFO - Job 569: Subtask add-db-data
[2022-09-11 21:41:14,091] {task_command.py:369} INFO - Running <TaskInstance: tcc_dag.add-db-data manual__2022-09-11T21:41:04.436761+00:00 [running]> on host b6ddae3e9f9e
[2022-09-11 21:41:14,174] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Michelle Mesquita
AIRFLOW_CTX_DAG_ID=tcc_dag
AIRFLOW_CTX_TASK_ID=add-db-data
AIRFLOW_CTX_EXECUTION_DATE=2022-09-11T21:41:04.436761+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-11T21:41:04.436761+00:00
[2022-09-11 21:41:14,191] {logging_mixin.py:115} INFO - Connecting to the MySQL database...
[2022-09-11 21:41:14,194] {logging_mixin.py:115} INFO - 2003 (HY000): Can't connect to MySQL server on 'localhost:3308' (99)
[2022-09-11 21:41:14,203] {logging_mixin.py:115} INFO - Connecting to the MySQL database...
[2022-09-11 21:41:14,205] {logging_mixin.py:115} INFO - 2003 (HY000): Can't connect to MySQL server on 'localhost:3308' (99)
[2022-09-11 21:41:14,214] {python.py:173} INFO - Done. Returned value was: (None, [])
[2022-09-11 21:41:14,249] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=tcc_dag, task_id=add-db-data, execution_date=20220911T214104, start_date=20220911T214113, end_date=20220911T214114
[2022-09-11 21:41:14,292] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-11 21:41:14,335] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
