[2022-09-08 23:35:49,609] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tcc_dag.snyk-sast-data manual__2022-09-08T23:35:46.655289+00:00 [queued]>
[2022-09-08 23:35:49,634] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tcc_dag.snyk-sast-data manual__2022-09-08T23:35:46.655289+00:00 [queued]>
[2022-09-08 23:35:49,635] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-09-08 23:35:49,637] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-09-08 23:35:49,638] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-09-08 23:35:49,661] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): snyk-sast-data> on 2022-09-08 23:35:46.655289+00:00
[2022-09-08 23:35:49,669] {standard_task_runner.py:52} INFO - Started process 264 to run task
[2022-09-08 23:35:49,688] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tcc_dag', 'snyk-sast-data', 'manual__2022-09-08T23:35:46.655289+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/tcc_dag-checkpoint.py', '--cfg-path', '/tmp/tmp3hk_uvou', '--error-file', '/tmp/tmpkybzxd3l']
[2022-09-08 23:35:49,692] {standard_task_runner.py:80} INFO - Job 120: Subtask snyk-sast-data
[2022-09-08 23:35:49,804] {task_command.py:369} INFO - Running <TaskInstance: tcc_dag.snyk-sast-data manual__2022-09-08T23:35:46.655289+00:00 [running]> on host 9a5942a886e3
[2022-09-08 23:35:50,002] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Michelle Mesquita
AIRFLOW_CTX_DAG_ID=tcc_dag
AIRFLOW_CTX_TASK_ID=snyk-sast-data
AIRFLOW_CTX_EXECUTION_DATE=2022-09-08T23:35:46.655289+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-08T23:35:46.655289+00:00
[2022-09-08 23:35:50,015] {logging_mixin.py:115} INFO - 0
[2022-09-08 23:35:50,032] {logging_mixin.py:115} INFO - 0
[2022-09-08 23:35:50,036] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/.ipynb_checkpoints/tcc_dag-checkpoint.py", line 31, in get_snyk_data
    for x in open("./project_id_snyk.txt", "r"):
FileNotFoundError: [Errno 2] No such file or directory: './project_id_snyk.txt'
[2022-09-08 23:35:50,052] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=tcc_dag, task_id=snyk-sast-data, execution_date=20220908T233546, start_date=20220908T233549, end_date=20220908T233550
[2022-09-08 23:35:50,089] {standard_task_runner.py:97} ERROR - Failed to execute job 120 for task snyk-sast-data ([Errno 2] No such file or directory: './project_id_snyk.txt'; 264)
[2022-09-08 23:35:50,140] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-08 23:35:50,221] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
