[2022-09-13 00:26:02,744] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tcc_dag.add-db-data manual__2022-09-13T00:25:52.544694+00:00 [queued]>
[2022-09-13 00:26:02,757] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tcc_dag.add-db-data manual__2022-09-13T00:25:52.544694+00:00 [queued]>
[2022-09-13 00:26:02,758] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-09-13 00:26:02,759] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-09-13 00:26:02,759] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-09-13 00:26:02,776] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): add-db-data> on 2022-09-13 00:25:52.544694+00:00
[2022-09-13 00:26:02,782] {standard_task_runner.py:52} INFO - Started process 29333 to run task
[2022-09-13 00:26:02,787] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tcc_dag', 'add-db-data', 'manual__2022-09-13T00:25:52.544694+00:00', '--job-id', '769', '--raw', '--subdir', 'DAGS_FOLDER/tcc_dag.py', '--cfg-path', '/tmp/tmpm5vec70h', '--error-file', '/tmp/tmp_akl1apm']
[2022-09-13 00:26:02,788] {standard_task_runner.py:80} INFO - Job 769: Subtask add-db-data
[2022-09-13 00:26:02,876] {task_command.py:369} INFO - Running <TaskInstance: tcc_dag.add-db-data manual__2022-09-13T00:25:52.544694+00:00 [running]> on host b6ddae3e9f9e
[2022-09-13 00:26:02,966] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Michelle Mesquita
AIRFLOW_CTX_DAG_ID=tcc_dag
AIRFLOW_CTX_TASK_ID=add-db-data
AIRFLOW_CTX_EXECUTION_DATE=2022-09-13T00:25:52.544694+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-13T00:25:52.544694+00:00
[2022-09-13 00:26:02,985] {logging_mixin.py:115} INFO - Connecting to the MySQL database...
[2022-09-13 00:26:03,021] {logging_mixin.py:115} INFO - Database connection closed.
[2022-09-13 00:26:03,039] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas/core/generic.py:5516: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

[2022-09-13 00:26:03,044] {logging_mixin.py:115} INFO - Connecting to the MySQL database...
[2022-09-13 00:26:03,076] {logging_mixin.py:115} INFO - Database connection closed.
[2022-09-13 00:26:03,095] {python.py:173} INFO - Done. Returned value was: None
[2022-09-13 00:26:03,112] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=tcc_dag, task_id=add-db-data, execution_date=20220913T002552, start_date=20220913T002602, end_date=20220913T002603
[2022-09-13 00:26:03,175] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-13 00:26:03,226] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
